[package]
name = "pft"
version = "0.1.0"
edition = "2021"

[dependencies]
colog = "1.3.0"
log = "0.4.22"
openssl = "0.10.64"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.120"
tokio = {version = "1.38.0", features = ["full"]}
