workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
quorum_diversity_k = 3
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 10
signature_max_delay_ms = 10000
num_crypto_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 5

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100

[node_config.evil_config]
simulate_byzantine_behavior = true
byzantine_start_block = 8000


[client_config]

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
num_requests = 100_000_000
request_config = "Blanks"

[[experiments]]
name = "pirateship"
repeats = 1
num_nodes = 7
num_clients = 2000
node_distribution = "uniform"
build_command = "make pirateship_logger_evil"
duration = 120


[[results]]
name = "tput_timeseries"
plotter = "crash_byz_tput_timeseries"
ramp_up = 20
ramp_down = 50
target_node = "node2"
force_parse = true
sample_rate = 10
output = "equivocation.pdf"

[[results.events]]
name = "first_equivocate"
pattern = "\\[WARN\\]\\[.*\\]\\[(.*)\\] Equivocated on block .*"
target = "node1"
description = "Equivocation\nstart"

[[results.events]]
name = "first_revolt"
pattern = "\\[INFO\\]\\[.*\\]\\[(.*)\\] Processing view change for view .* from .*"
target = "node1"
occurrence_num = 6 # 5 needed for first view change; 1 for the second
description = "First follower\ntimeout"

[[results.events]]
name = "moved_view"
pattern = "\\[WARN\\]\\[.*\\]\\[(.*)\\] Moved to new view .* with leader.*"
target = "node1"
occurrence_num = 2
description = "Leader\nstep down"

[[results.events]]
name = "view_stabilized"
patterns = [
    "\\[INFO\\]\\[.*\\]\\[(.*)\\] View stabilised.*",
    "\\[INFO\\]\\[.*\\]\\[(.*)\\]View fast forwarded to .* stable\\? true"
]
occurrence_num = 2
target = "node1"
description = "New view\nstabilized"