workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 250
commit_index_gap_hard = 500
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 10
signature_max_delay_ms = 102 # roughly batch_max_delay_ms * signature_max_delay_blocks
num_crypto_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 2

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100
checkpoint_interval_ms = 1000

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]
full_duplex = true
client_sub_id = 0       # This is filled up later by the caller code.

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
num_requests = 100_000_000
request_config = "Blanks"
max_concurrent_requests = 32

[[experiments]]
name = "fast_path"
repeats = 1
num_nodes = 7
node_distribution = "uniform"
build_command = "make"
duration = 90

[experiments.sweeping_parameters]
num_clients = [50, 100, 200, 400, 500, 600]




[[experiments]]
name = "slow_path"
repeats = 1
num_nodes = 7
node_distribution = "uniform"
build_command = "make pirateship_logger_nofast"
duration = 90

[experiments.sweeping_parameters]
num_clients = [50, 100, 200, 400, 500, 600]




[[results]]
name = "tput_latency_client_sweep"
plotter = "tput_latency_sweep"
ramp_up = 15
ramp_down = 15
output = "fast_path_experiment.pdf"
force_parse = true
# skip_indices = [4]

[results.legends]
# Experiment group to legend mapping
slow_path = "Slow Audit+onlybyz"
fast_path = "Commit+Fast Audit+byz"
