workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 25000
commit_index_gap_hard = 50000
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 50
signature_max_delay_ms = 102000 # roughly batch_max_delay_ms * signature_max_delay_blocks
num_crypto_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 2

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100
checkpoint_interval_ms = 1000

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]
full_duplex = true
client_sub_id = 0       # This is filled up later by the caller code.

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
request_config = "Blanks"
max_concurrent_requests = 16

# [[experiments]]
# name = "pirateship_cr_1"
# repeats = 1
# num_nodes = 7
# num_clients = 600
# node_distribution = "uniform"
# build_command = "make"
# duration = 60
# seq_start = 2

# [experiments.node_config.consensus_config]
# num_crypto_workers = 1

# [experiments.sweeping_parameters.node_config.consensus_config]
# # signature_max_delay_blocks = [1, 5, 10, 50]
# signature_max_delay_blocks = [10]

[[experiments]]
name = "pirateship_cr_5"
repeats = 3
num_nodes = 7
num_clients = 200
node_distribution = "uniform"
build_command = "make"
duration = 60

[experiments.node_config.consensus_config]
num_crypto_workers = 5

[experiments.sweeping_parameters.node_config.consensus_config]
signature_max_delay_blocks = [1, 2, 5, 10, 20, 50]
# signature_max_delay_blocks = [50]



# [[experiments]]
# name = "pirateship_cr_10"
# repeats = 1
# num_nodes = 7
# num_clients = 600
# node_distribution = "uniform"
# build_command = "make"
# duration = 60

# [experiments.node_config.consensus_config]
# num_crypto_workers = 10

# [experiments.sweeping_parameters.node_config.consensus_config]
# signature_max_delay_blocks = [1, 5, 10, 50]



# [[results]]
# name = "tput_latency_client_sweep"
# plotter = "tput_latency_sweep"
# ramp_up = 15
# ramp_down = 15
# output = "lan_final.pdf"
# force_parse = true


# [results.legends]
# pirateship_cr_1 = "1 crypto thread"
# pirateship_cr_5 = "Commit+Audit+byz"
# # pirateship_cr_5 = "Commit"
# pirateship_cr_10 = "10 crypto threads"

# [results.font]
# size = 55

[[results]]
name = "tput_rw_sweep"
plotter = "stacked_bar_graph"
ramp_up = 15
ramp_down = 15
output = "sig_sensitivity.pdf"
xlabels = ["1", "2", "5", "10", "20", "50"]
xtitle = "Signature Intervals"
# xlabels = ["25R-75W", "50R-50W"]
force_parse = true

[results.legends]
pirateship_cr_5 = "pirateship(n=7)+Audit+onlybyz"
# signed_raft = "signed_raft(n=5)+byz"
