workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "wan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000

[[deployment_config.custom_layout]]
name = "c1"
nodes_per_region = [1, 1, 1, 1, 0]

[[deployment_config.custom_layout]]
name = "c2"
nodes_per_region = [2, 2, 2, 1, 0]

[[deployment_config.custom_layout]]
name = "c3"
nodes_per_region = [2, 2, 2, 2, 1]



[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 1000
commit_index_gap_hard = 500000
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 10
signature_max_delay_ms = 502 # roughly batch_max_delay_ms * signature_max_delay_blocks
num_crypto_workers = 5
view_timeout_ms = 30000
batch_max_delay_ms = 5

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100
checkpoint_interval_ms = 1000

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]
full_duplex = true
client_sub_id = 0       # This is filled up later by the caller code.

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
num_requests = 100_000_000
request_config = "Blanks"
max_concurrent_requests = 32

# [[experiments]]
# name = "c1"
# repeats = 1
# num_nodes = 4
# node_distribution = "c1"
# client_region = 0
# build_command = "make"
# duration = 60

# [experiments.node_config.consensus_config]
# liveness_u = 1

# [experiments.sweeping_parameters]
# num_clients = [100, 200, 400, 500, 700, 1000]

# [[experiments]]
# name = "c2"
# repeats = 1
# num_nodes = 7
# node_distribution = "c2"
# client_region = 0
# build_command = "make"
# duration = 60
# seq_start = 5

# [experiments.node_config.consensus_config]
# liveness_u = 2

# [experiments.sweeping_parameters]
# # num_clients = [60, 80, 100, 120, 150]
# num_clients = [160, 170, 180, 200]


[[experiments]]
name = "c3"
repeats = 1
num_nodes = 9
node_distribution = "c3"
client_region = 0
build_command = "make"
duration = 60
seq_start = 9

[experiments.node_config.consensus_config]
liveness_u = 3

[experiments.sweeping_parameters]
# num_clients = [80, 100, 120, 150, 170, 200, 220, 250, 270, 300, 320, 350]
num_clients = [320, 330, 340, 350]


[[results]]
name = "tput_latency_client_sweep"
plotter = "tput_latency_sweep"
ramp_up = 10
ramp_down = 10
output = "wan_experiment.pdf"
force_parse = true

[results.legends]
c1 = "C1+C1-aud+byz"
c2 = "C2+C2-aud+byz"
c3 = "C3+C3-aud+byz"

[results.font]
size = 55
