workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "wan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000

[[deployment_config.custom_layout]]
name = "c1"
nodes_per_region = [1, 1, 1, 1, 0]

[[deployment_config.custom_layout]]
name = "c2"
nodes_per_region = [2, 2, 2, 1, 0]

[[deployment_config.custom_layout]]
name = "c3"
nodes_per_region = [2, 2, 2, 2, 1]



[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
quorum_diversity_k = 3
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 50
signature_max_delay_ms = 10000
vote_processing_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 20

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]

[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
num_requests = 100_000_000
request_config = "Blanks"

[[experiments]]
name = "c1"
repeats = 3
num_nodes = 4
node_distribution = "c1"
client_region = 0
build_command = "make"
duration = 120

[experiments.node_config.consensus_config]
liveness_u = 1

[experiments.sweeping_parameters]
num_clients = [100, 200, 500, 1000, 2000, 3000, 5000, 7000, 9000]

[[experiments]]
name = "c2"
repeats = 3
num_nodes = 7
node_distribution = "c1"
client_region = 0
build_command = "make"
duration = 120

[experiments.node_config.consensus_config]
liveness_u = 2

[experiments.sweeping_parameters]
num_clients = [100, 200, 500, 1000, 2000, 3000, 5000, 7000, 9000]

[[experiments]]
name = "c3"
repeats = 3
num_nodes = 9
node_distribution = "c1"
client_region = 0
build_command = "make"
duration = 120

[experiments.node_config.consensus_config]
liveness_u = 3

[experiments.sweeping_parameters]
num_clients = [100, 200, 500, 1000, 2000, 3000, 5000, 7000, 9000]

[[results]]
name = "tput_latency_client_sweep"
plotter = "tput_latency_sweep"
ramp_up = 30
ramp_down = 30
output = "wan_experiment.pdf"

[results.legends]
c1 = "C1+byz"
c2 = "C2+byz"
c3 = "C3+byz"

[results.font]
size = 55
