workdir = "deployment_artifacts"
project_home = "https://github.com/grapheo12/pirateship"

[deployment_config]
mode = "lan"
ssh_key = "cluster_key.pem"
ssh_user = "pftadmin"
node_port_base = 3000


[node_config]

[node_config.net_config]
client_max_retry = 10

[node_config.rpc_config]
recv_buffer_size = 32768
channel_depth = 1000

[node_config.consensus_config]
commit_index_gap_soft = 250
commit_index_gap_hard = 5000
liveness_u = 2
max_backlog_batch_size = 1000
signature_max_delay_blocks = 10
signature_max_delay_ms = 10000
num_crypto_workers = 5
view_timeout_ms = 4000
batch_max_delay_ms = 2

[node_config.consensus_config.log_storage_config.RocksDB]
write_buffer_size = 2147483648
max_write_buffer_number = 1
max_write_buffers_to_merge = 1

[node_config.app_config]
logger_stats_report_ms = 100
checkpoint_interval_ms = 1000

[node_config.evil_config]
simulate_byzantine_behavior = false
byzantine_start_block = 0


[client_config]
full_duplex = true
client_sub_id = 0       # This is filled up later by the caller code.


[client_config.net_config]
client_max_retry = 10

[client_config.workload_config]
max_concurrent_requests = 16


[client_config.workload_config.request_config.KVReadWriteYCSB]
num_keys = 3000
num_fields = 1
val_size = 100
linearizable_reads = false
byz_commit_ratio = 0.0
load_phase = true
zipf_exponent = 0.99
read_ratio = 0.0


[[experiments]]
name = "pirateship1"
repeats = 1
num_nodes = 7
# num_clients = 800
node_distribution = "uniform"
build_command = "make pirateship_kvs"
duration = 60

[experiments.sweeping_parameters]
num_clients = [800]



# # [experiments.sweeping_parameters.client_config.workload_config.request_config.KVReadWriteYCSB]
# # read_ratio = [0.0, 0.25, 0.5, 0.75, 1.0]
# # read_ratio = [0.25]


# [[experiments]]
# name = "signed_raft1"
# repeats = 1
# num_nodes = 5
# # num_clients = 800
# node_distribution = "uniform"
# build_command = "make signed_raft_kvs"
# duration = 60

# # [experiments.sweeping_parameters.client_config.workload_config.request_config.KVReadWriteYCSB]
# # read_ratio = [0.0, 0.25, 0.5, 0.75, 1.0]
# # read_ratio = [0.25]

# [experiments.sweeping_parameters]
# num_clients = [100, 200, 400, 800, 1000, 1200]





[[results]]
name = "tput_latency_client_sweep"
plotter = "tput_latency_sweep"
ramp_up = 15
ramp_down = 15
output = "lan_final.pdf"
force_parse = true
# skip_indices = [0, 1]

[results.legends]
# Experiment group to legend mapping
pirateship1 = "ps(sig=10)"
# pirateship_sig_1 = "ps(sig=1)+byz"
# hotstuff = "hotstuff+onlybyz"
# engraft = "engraft+onlybyz"
# signed_raft1 = "signed_raft"
# autobahn = "autobahn"

[results.font]
size = 55
